const path = require('path')
const fn = require('./concerns')
const folder = path.join(__dirname, '..', 'subtitles')
const symbols = ['.', '?', '!', '-', ',', '"', '♪', '&', '_', '<i>', '</i>', '\r', '[', ']', '(', ')']

fn.readDir(folder)
  .then(fn.filesFilter('.srt'))
  .then(fn.readFiles)
  .then(fn.mergeContent)
  .then(fn.separateBy('\n'))
  .then(fn.removeEmpty)
  .then(fn.removeWithPattern('-->'))
  .then(fn.removeOnlyNumbers)
  .then(fn.removeChars(symbols))
  .then(fn.mergeContent)
  .then(fn.separateBy(' '))
  .then(fn.removeEmpty)
  .then(fn.removeOnlyNumbers)
  .then(fn.groupBy)
  .then(fn.orderBy('qty', 'desc'))
  .then(console.log)
